esd:
  port:
    http:
      name: http
      host: 0.0.0.0
      port: 8080
      sock_type: 1
      open_http_protocol: true
scheduled:
  min_interval_time: 1000
  scheduled_tasks:
    test:
      name: test
      expression: '* * * * * *'
      class_name: ESD\Plugins\Scheduled\ExampleClass\TestScheduledTask
      function_name: test
      process_group: all

scan:
  include_paths:
    exampleClass: /mnt/c/Users/administrato/PhpstormProjects/scheduled-plugin/exampleClass
